# Generated by Django 5.0.1 on 2024-01-24 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True, max_length=150)),
                ("math_send_time", models.DateTimeField()),
                ("math_deadline", models.DateTimeField()),
                ("math_question_link", models.URLField()),
                ("lesson_send_time", models.DateTimeField()),
                ("lesson_deadline", models.DateTimeField()),
                ("lesson_question_link", models.URLField()),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("math_sub_link", models.URLField(blank=True, null=True)),
                ("math_sub_date", models.DateTimeField(blank=True, null=True)),
                ("lesson_sub_link", models.URLField(blank=True, null=True)),
                ("lesson_sub_date", models.DateTimeField(blank=True, null=True)),
                ("missed_deadline_count", models.IntegerField(default=0)),
                ("on_time_submission_count", models.IntegerField(default=0)),
                (
                    "assigmnets",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="student_work.assignments",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_name",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
