# Generated by Django 5.0.1 on 2024-01-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student_work", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignments",
            name="is_submitted",
            field=models.BooleanField(default=False),
        ),
    ]
