# Generated by Django 5.0.1 on 2024-02-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='discription',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
