# Generated by Django 5.0.1 on 2024-02-09 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cbv", "0002_alter_submission_submission_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="created_by",
            new_name="created_at",
        ),
    ]
