# Generated by Django 5.0.1 on 2024-02-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0002_assignment_discription_assignment_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='discription',
            new_name='description',
        ),
    ]
