# Generated by Django 5.0.1 on 2024-02-05 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0003_rename_discription_assignment_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='type',
            new_name='type_field',
        ),
    ]
