# Generated by Django 5.0.1 on 2024-02-05 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0004_rename_type_assignment_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
