# Generated by Django 5.0.1 on 2024-02-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0005_assignment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='Submission_link',
            field=models.URLField(null=True),
        ),
    ]
